---
title: "Figure 1: disparity through time - simplified and for appendix"
author: "Natalie Cooper"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

```{r, message = FALSE}
library(tidyverse)
```

Pick the slug

```{r}
slug <- "Brusatte2014"
```

Load the data 

```{r}
out1 <- readRDS(file = paste0("../outputs/epoch.", slug, ".Rda"))

strat <- out1$results$stratigraphy
duration <- out1$results$duration
number <- out1$results$number
```

Get the data into the correct format to plot

```{r}
# Stratigraphy
# Get ages for the bins, go for the midpoints
x <- str_split(strat$subset, " - ") 
y <- map(x, as.numeric)
z <- map(y, mean)

# Modify data - add midpoints, remove missing data, filter to just two models
strat2 <- 
  strat %>%
  mutate(time = unlist(z)) %>%
  filter(bs.median != 0 & !is.na(bs.median)) %>%
  filter(model == "equalbins" | model == "proximity")

# Duration
x <- str_split(duration$subset, " - ") 
y <- map(x, as.numeric)
z <- map(y, mean)

duration2 <- 
  duration %>%
  mutate(time = unlist(z)) %>%
  filter(bs.median != 0 & !is.na(bs.median)) %>%
  filter(model == "equalbins" | model == "proximity")

# Number
x <- str_split(number$subset, " - ") 
y <- map(x, as.numeric)
z <- map(y, mean)

number2 <- 
  number %>%
  mutate(time = unlist(z)) %>%
  filter(bs.median != 0 & !is.na(bs.median)) %>%
  filter(model == "equalbins" | model == "proximity")
```

Make plots in preparation for larger grid plot below

```{r}

brusatte_base <- 
  ggplot(strat2, aes(y = bs.median, x = time, colour = model)) +
  theme_classic(base_size = 16) + 
  xlab("Time (MYA)") + 
  ylab("Disparity") + 
  scale_y_continuous(breaks = seq(0, 10, 2), 
                     labels = seq(0, 10, 2)) +
  scale_x_reverse(limits = c(100, 0)) +
  expand_limits(x = 0, y = 3) +
  theme(legend.position = "none")

brusatte_s <- 
  brusatte_base +
  geom_point(data = strat2, size = 2, alpha = 0.8) +
  geom_errorbar(data = strat2, aes(ymin = `2.5%`, ymax = `97.5%`), width = 1, alpha = 0.8)
  
brusatte_d <- 
  brusatte_base +
  geom_point(data = duration2, size = 2, alpha = 0.8) +
  geom_errorbar(data = duration2, aes(ymin = `2.5%`, ymax = `97.5%`), width = 1, alpha = 0.8)

brusatte_n <- 
  brusatte_base +
  geom_point(data = number2, size = 2, alpha = 0.8) +
  geom_errorbar(data = number2, aes(ymin = `2.5%`, ymax = `97.5%`), width = 1, alpha = 0.8)

```

