---
title: "Dataset table"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 12
---

# Compiling the dataset table

Loading the packages

```{r}
library(xtable)
library(Claddis)
library(ape)
library(dispRity)
```

Loading the data:

```{r}
## Getting the data
slugs <- list("Beck2014", "Brusatte2014", "Bapst2016", "Wright2017")

## Matrices lists
matrices <- lapply(slugs, function(slug) ReadMorphNexus(paste0("../data/matrices/", slug, ".nex"))$matrix )

## Trees lists
trees <- lapply(slugs, function(slug) read.nexus(paste0("../data/processed/tree.", slug, ".tre")))
## Adding Wright's tree age
trees[[4]]$root.time <- 485.4
```

## Data set table (Table 1)

```{r}
## variable names
rownames <- c("Group", "# taxa", "# characters", "Age range (MYA)", "Mass extinction (MYA)", "Reference", "Data reference")

## Dataset names
dataset <- unlist(slugs)

## Groups
group <- c("mammals", "theropods", "theropods", "crinoids")

## Number of taxa
ntaxa <- unlist(lapply(matrices, nrow))

## Number of characters
mcharacters <- unlist(lapply(matrices, ncol))

## Age ranges
age_ranges <- lapply(trees, function(tree) rev(range(tree.age(tree)$age)))
age_ranges <- unlist(lapply(age_ranges, function(age) paste(age, collapse = " - ")))

## Mass extinction
mass <- c("66 (K-Pg)", "NA", "NA", "443 (O-S)")

## References (to be filled in LaTeX)
reference <- rep("", length(slugs))
dataref <- rep("", length(slugs))

## Formatting the table
table_out <- data.frame(group, ntaxa, mcharacters, age_ranges, mass, reference, dataref)
table_out <- t(table_out)
colnames(table_out) <- dataset
rownames(table_out) <- rownames

## Table caption
table_caption <- "Details of the datasets used in this study. Note that although Brusatte2014 and Bapst2016 cross the Cretaceaous Palaeogene (K-Pg) mass extinction there are not enough taxa post K-Pg to investigate the effects of the mass extinction on disparity."

sink(file = "../manuscript/tables/raw_datasets.tex")
xtable(table_out, caption = table_caption)
sink()
```

This produces a nicely formatted LaTeX table. Some edits will need to be made before it is incorporated into a document but it contains all the basic information required.

