---
title: "Wilcoxon results tables - text and appendix"
author: "Natalie Cooper"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 12
---

# Compiling the tables for the paper

Loading the packages

```{r}
library(xtable)
library(Claddis)
library(ape)
library(dispRity)
library(tidyverse)
```

Loading the data:

```{r}
## Getting the data
slugs <- list("Beck2014", "Brusatte2014", "Bapst2016", "Wright2017")

## Wilcox results
wilk <- lapply(slugs, function(slug) read.csv(paste0("../outputs/wilcox.", slug, ".csv"), 
                                              header = FALSE))

```

Manipulate the data into the format we need.

```{r}
# Stick p values and W values together
# Replace p values with *
p.values.function <- function(data){ 
  for (i in 1:length(data$V2)){
    if(data$V2[i] < 0.05 & data$V2[i] > 0.01){data$V2[i] <- "*"}
    if(data$V2[i] < 0.01 & data$V2[i] > 0.001){data$V2[i] <- "**"}
    if(data$V2[i] < 0.001){data$V2[i] <- "***"}
    if(data$V2[i] > 0.05){data$V2[i] <- ""}
  }
  data$V6 <- paste0(data$V1, data$V2)
return(data)
}

# Extract proximity and gradual split models
# Remove excess columns
# Add model column name
fix.wilcox <- function(data){
  data %>%
  select(-c(V1,V2)) %>%
  filter(V3 == "proximity" | V3 == "gradual.split") %>%
  spread(V4, V6) %>%
  arrange(V5) %>%
  rename(model = V3) %>%
  rename(period = V5)  
}
  
wilk2 <- purrr::map(wilk, p.values.function)
wilk3 <- purrr::map_df(wilk2, fix.wilcox)
wilk3$dataset <- c(rep(unlist(slugs)[1], 4), rep(unlist(slugs)[2], 4), 
                   rep(unlist(slugs)[3], 4), rep(unlist(slugs)[4], 4))

```

## Create table

```{r}
## variable names
colnames <- c("Dataset", "Period", "Method", "Stratigraphy", "Duration", "Number")

## Formatting the table
table_out <- data.frame(wilk3$dataset, wilk3$period, wilk3$model, wilk3$stratigraphy,
                        wilk3$duration, wilk3$number)
colnames(table_out) <- colnames

## Table caption
table_caption <- "Results of paired Wilcoxon tests investigating whether disparities calculated using time bins are significantly different to those calculated using time-slices. Time-slices used either a  punctuated (‘proximity’ method) or gradual (‘gradual.split’ method) model of evolution. Stratigraphy uses unequal time bins or non-equidistant time-slices, where the width of the bin, or the interval between slices, is equivalent to stratigraphic ages or epochs. Duration uses equal time bins or equidistant time-slices, where the width of the bin, or the interval between slices, is the average duration of stratigraphic ages or epochs in the time frame of the dataset. Number uses equal time bins or equidistant time-slices, where the number of bins, or the number of slices, is the average number of stratigraphic ages or epochs in the time frame of the dataset. P-values were Bonferroni corrected. ***p < 0.001. Results for other time-slicing methods are in the Supporting Information Appendix S2: Table A1."

## Save
sink(file = "../manuscript/tables/raw_wilcox.tex")
print(xtable(table_out, caption = table_caption), include.rownames = FALSE)
sink()
```

## Repeat for appendix tables with all models

Manipulate the data into the format we need.

```{r}
# Remove excess columns
# Add model column name
fix.wilcox.appendix <- function(data){
  data %>%
  select(-c(V1,V2)) %>%
  spread(V4, V6) %>%
  arrange(V5) %>%
  rename(model = V3) %>%
  rename(period = V5)
}
  
wilk2 <- purrr::map(wilk, p.values.function)
wilk3 <- purrr::map_df(wilk2, fix.wilcox.appendix)
wilk3$dataset <- c(rep(unlist(slugs)[1], 12), rep(unlist(slugs)[2], 12), 
                   rep(unlist(slugs)[3], 12), rep(unlist(slugs)[4], 12))

```

## Create table for all data

```{r}
## variable names
colnames <- c("Dataset", "Period", "Method", "Stratigraphy", "Duration", "Number")

## Formatting the table
table_out <- data.frame(wilk3$dataset, wilk3$period,
                        wilk3$model, wilk3$stratigraphy,
                        wilk3$duration, wilk3$number)
colnames(table_out) <- colnames

## Table caption
table_caption <- "Results of paired Wilcoxon tests investigating whether disparities calculated using time bins are significantly different to those calculated using time-slices. Time-slices used one of six methods. Stratigraphy uses unequal time bins or non-equidistant time-slices, where the width of the bin, or the interval between slices, is equivalent to stratigraphic ages or epochs. Duration uses equal time bins or equidistant time-slices, where the width of the bin, or the interval between slices, is the average duration of stratigraphic ages or epochs in the time frame of the dataset. Number uses equal time bins or equidistant time-slices, where the number of bins, or the number of slices, is the average number of stratigraphic ages or epochs in the time frame of the dataset. . P-values were Bonferroni corrected. ***p < 0.001."

## Save
sink(file = "../manuscript/tables/raw_wilcox_appendix.tex")
print(xtable(table_out, caption = table_caption), include.rownames = FALSE)
sink()
```

These tables are LaTeX format and can be added into documents after a small amount of manipulation.
