---
title: "Extinction effect"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

# Compiling the figures for the paper

Loading the code:

```{r}
library(ape)
library(dispRity)
source("../functions/figures_fun.R")

## ggplot colors
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
```

## Extinction effect figures

Initialising the slug and loading the data:

```{r, eval = FALSE}
## Slugs (choose one)
slug <- "Beck2014"
# slug <- "Brusatte2014"
# slug <- "Bapst2016"
# slug <- "Wright2017"

data <- read.csv(paste0("../outputs/extinction.", slug, ".csv"), stringsAsFactors = FALSE)
```

Single plots:

```{r, fig.width = 6, fig.height = 6, eval = FALSE}
colours <- c("grey", "white", "black") #Signif, non-signif, NA
plot.extinction(data, type = "age", xaxis = TRUE, yaxis = TRUE, xaxis2 = TRUE, main = slug, cols = colours)
```

Multiple plots:

```{r, fig.width = 12, fig.height = 4}

## Names of the datasets
slugs <- as.list(c("Beck2014", "Brusatte2014", "Bapst2016", "Wright2017"))

## Load all the data
data_list <- lapply(slugs, function(slug) read.csv(paste0("../outputs/extinction.", slug, ".csv"), stringsAsFactors = FALSE))

## Set up the colours (yeah, they're ugly for now)
colours <- c(gg_color_hue(2), "white") #Signif, non-signif, NA

## Plot all the results
pdf("../manuscript/figures/fig-extinction-effect.pdf", width = 12, height = 4)  
multi.plot.extinction(data_list, type = c("age", "epoch"), data.names = unlist(slugs), cols = colours)
dev.off()
```


















