---
title: "Disparity peaks - for appendix"
author: "Natalie Cooper"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 12
---

```{r, message = FALSE}
library(tidyverse)
library(gridExtra)
library(grid)
source("../functions/multiplot_fun.R")
```

# Beck 2014

```{r}
slug <- "Beck2014"
```

Load the data 

```{r}
data_max <- read.csv(paste0("../outputs/peaks.max.", slug, ".csv"))
data_max$bin_type <- gsub("stratigraphy", "Stratigraphy", data_max$bin_type) 
data_max$bin_type <- gsub("duration", "Duration", data_max$bin_type) 
data_max$bin_type <- gsub("number", "Number", data_max$bin_type) 
data_max$bin_type <- as.factor(data_max$bin_type)
```

# Modify the data
```{r}
# Get ages for the bins, go for the midpoints
x <- str_split(data_max$subsets, " - ") 
y <- map(x, as.numeric)
z1 <- map(y, max)
z2 <- map(y, min)

# Modify data - add midpoints, remove missing data, filter to just three models
data_max2 <- 
  data_max %>%
  mutate(time1 = unlist(z1)) %>%
  mutate(time2 = unlist(z2)) %>%
  filter(bs.median != 0 & !is.na(bs.median)) %>%
  mutate(bin_type = relevel(data_max$bin_type, ref = 'Stratigraphy')) %>%
  mutate(model = relevel(data_max$model, ref = 'equalbins')) #%>%
  #filter(model == "equalbins" | model == "proximity" | model == "gradual.split")
  
data_max2_age <- filter(data_max2, stratigraphy == "Age")

data_max2_epoch <- filter(data_max2, stratigraphy == "Epoch")
```

```{r}
# Make mini dataframe for annotations
ann_text <- data.frame(model = "bins", time1 = 10, bin_type = "Stratigraphy")

beck_peaks <- 
  ggplot(data_max2_epoch, aes(y = time1, x = model, colour = model)) +
  theme_classic(base_size = 12) +
  geom_point() +
  geom_point(aes(y = time2, x = model, colour = model)) +
  facet_wrap(~bin_type, ncol = 3) +
  #scale_x_discrete(labels = c("bins", "gradual", "proximity")) +
 # expand_limits(x = 0, y = c(0,1)) +
 theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
       axis.text.x = element_blank(),
        #legend.position = "none",
        panel.spacing = unit(0, "lines"),
        panel.border = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(size = 14), 
       strip.text.x = element_text(size = 12)) +
  geom_text(data = ann_text, aes(x = 1, y = 10, 
            label = "Beck2012"), col = "black") +
  scale_colour_viridis(discrete = TRUE, direction = -1, end = 0.8)

beck_peaks_age <- 
  ggplot(data_max2_age, aes(y = time1, x = model, colour = model)) +
  theme_classic(base_size = 12) +
  geom_point() +
  geom_point(aes(y = time2, x = model, colour = model)) +
  facet_wrap(~bin_type, ncol = 3) +
  #scale_x_discrete(labels = c("bins", "gradual", "proximity")) +
 # expand_limits(x = 0, y = c(0,1)) +
 theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        #legend.position = "none",
        panel.spacing = unit(0, "lines"),
        panel.border = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(size = 14),
       strip.text.x = element_text(size = 12)) +
  geom_text(data = ann_text, aes(x = 1, y = 10, 
            label = "Beck2012"), col = "black") +
  scale_colour_viridis(discrete = TRUE, direction = -1, end = 0.8)
```

# Brusatte 2014

```{r}
slug <- "Brusatte2014"
```

Load the data 

```{r}
data_max <- read.csv(paste0("../outputs/peaks.max.", slug, ".csv"))
```
```{r}
# Get ages for the bins, go for the midpoints
x <- str_split(data_max$subsets, " - ") 
y <- map(x, as.numeric)
z1 <- map(y, max)
z2 <- map(y, min)

# Modify data - add midpoints, remove missing data, filter to just three models
data_max2 <- 
  data_max %>%
  mutate(time1 = unlist(z1)) %>%
  mutate(time2 = unlist(z2)) %>%
  filter(bs.median != 0 & !is.na(bs.median)) %>%
  mutate(bin_type = relevel(data_max$bin_type, ref = 'stratigraphy')) %>%
  mutate(model = relevel(data_max$model, ref = 'equalbins'))#%>%
  #filter(model == "equalbins" | model == "proximity" | model == "gradual.split") 

data_max2_age <- filter(data_max2, stratigraphy == "Age")

data_max2_epoch <- filter(data_max2, stratigraphy == "Epoch")
```

```{r}
# Make mini dataframe for annotations
ann_text <- data.frame(model = "bins", time1 = 10, bin_type = "stratigraphy")

brusatte_peaks <- 
  ggplot(data_max2_epoch, aes(y = time1, x = model, colour = model)) +
  theme_classic(base_size = 12) +
  geom_point() +
  geom_point(aes(y = time2, x = model, colour = model)) +
  facet_wrap(~bin_type, ncol = 3) +
  #scale_x_discrete(labels = c("bins", "gradual", "proximity")) +
  expand_limits(y = 0) +
 theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
       axis.text.x = element_blank(), 
       legend.position = "none", 
       panel.spacing = unit(0, "lines"),
        panel.border = element_blank(),
        strip.text = element_blank()) +
 geom_text(data = ann_text, aes(x = 1, y = 20, 
            label = "    Brusatte2014"), col = "black") +
  scale_colour_viridis(discrete = TRUE, direction = -1, end = 0.8)

brusatte_peaks_age <- 
  ggplot(data_max2_age, aes(y = time1, x = model, colour = model)) +
  theme_classic(base_size = 12) +
  geom_point() +
  geom_point(aes(y = time2, x = model, colour = model)) +
  facet_wrap(~bin_type, ncol = 3) +
  #scale_x_discrete(labels = c("bins", "gradual", "proximity")) +
  expand_limits(y = 0) +
 theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none", 
       axis.text.x = element_blank(),
       panel.spacing = unit(0, "lines"),
        panel.border = element_blank(),
        strip.text = element_blank()) +
 geom_text(data = ann_text, aes(x = 1, y = 20, 
            label = "    Brusatte2014"), col = "black") +
  scale_colour_viridis(discrete = TRUE, direction = -1, end = 0.8)
```

# Bapst 2016

```{r}
slug <- "Bapst2016"
```

Load the data 

```{r}
data_max <- read.csv(paste0("../outputs/peaks.max.", slug, ".csv"))
```
```{r}
# Get ages for the bins, go for the midpoints
x <- str_split(data_max$subsets, " - ") 
y <- map(x, as.numeric)
z1 <- map(y, max)
z2 <- map(y, min)

# Modify data - add midpoints, remove missing data, filter to just three models
data_max2 <- 
  data_max %>%
  mutate(time1 = unlist(z1)) %>%
  mutate(time2 = unlist(z2)) %>%
  filter(bs.median != 0 & !is.na(bs.median)) %>%
  mutate(bin_type = relevel(data_max$bin_type, ref = 'stratigraphy')) %>%
  mutate(model = relevel(data_max$model, ref = 'equalbins'))#%>%
  #filter(model == "equalbins" | model == "proximity" | model == "gradual.split") 

data_max2_age <- filter(data_max2, stratigraphy == "Age")

data_max2_epoch <- filter(data_max2, stratigraphy == "Epoch")
```

```{r}
bapst_peaks <- 
  ggplot(data_max2_epoch, aes(y = time1, x = model, colour = model)) +
  theme_classic(base_size = 12) +
  geom_point() +
  geom_point(aes(y = time2, x = model, colour = model)) +
  facet_wrap(~bin_type, ncol = 3) +
 # scale_x_discrete(labels = c("bins", "gradual", "proximity")) +
 # expand_limits(x = 0, y = c(0,1)) +
 theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none",
       axis.text.x = element_blank(),
       panel.spacing = unit(0, "lines"),
        panel.border = element_blank(),
        strip.text = element_blank()) +
 geom_text(data = ann_text, aes(x = 1, y = 72, 
            label = "Bapst2016"), col = "black") +
  scale_colour_viridis(discrete = TRUE, direction = -1, end = 0.8)

bapst_peaks_age <- 
  ggplot(data_max2_age, aes(y = time1, x = model, colour = model)) +
  theme_classic(base_size = 12) +
  geom_point() +
  geom_point(aes(y = time2, x = model, colour = model)) +
  facet_wrap(~bin_type, ncol = 3) +
  #scale_x_discrete(labels = c("bins", "gradual", "proximity")) +
 # expand_limits(x = 0, y = c(0,1)) +
 theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none",
       axis.text.x = element_blank(),
       panel.spacing = unit(0, "lines"),
        panel.border = element_blank(),
        strip.text = element_blank()) +
 geom_text(data = ann_text, aes(x = 1, y = 72, 
            label = "Bapst2016"), col = "black") +
  scale_colour_viridis(discrete = TRUE, direction = -1, end = 0.8)
```

# Wright 2017

```{r}
slug <- "Wright2017"
```

Load the data 

```{r}
data_max <- read.csv(paste0("../outputs/peaks.max.", slug, ".csv"))
```
```{r}
# Get ages for the bins, go for the midpoints
x <- str_split(data_max$subsets, " - ") 
y <- map(x, as.numeric)
z1 <- map(y, max)
z2 <- map(y, min)

# Modify data - add midpoints, remove missing data, filter to just three models
data_max2 <- 
  data_max %>%
  mutate(time1 = unlist(z1)) %>%
  mutate(time2 = unlist(z2)) %>%
  filter(bs.median != 0 & !is.na(bs.median)) %>%
  mutate(bin_type = relevel(data_max$bin_type, ref = 'stratigraphy')) %>%
  mutate(model = relevel(data_max$model, ref = 'equalbins'))#%>%
  #filter(model == "equalbins" | model == "proximity" | model == "gradual.split") 

data_max2_age <- filter(data_max2, stratigraphy == "Age")

data_max2_epoch <- filter(data_max2, stratigraphy == "Epoch")
```

```{r}
wright_peaks <- 
  ggplot(data_max2_epoch, aes(y = time1, x = model, colour = model)) +
  theme_classic(base_size = 12) +
  geom_point() +
  geom_point(aes(y = time2, x = model, colour = model)) +
  facet_wrap(~bin_type, ncol = 3) +
  #scale_x_discrete(labels = c("bins", "gradual", "proximity")) +
 expand_limits(y = c(455, 480)) +
 theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none",
       axis.text.x = element_blank(),
       panel.spacing = unit(0, "lines"),
        panel.border = element_blank(),
        strip.text = element_blank()) +
 geom_text(data = ann_text, aes(x = 1, y = 460, 
            label = " Wright2017"), col = "black") +
  scale_colour_viridis(discrete = TRUE, direction = -1, end = 0.8)   

wright_peaks_age <- 
  ggplot(data_max2_age, aes(y = time1, x = model, colour = model)) +
  theme_classic(base_size = 12) +
  geom_point() +
  geom_point(aes(y = time2, x = model, colour = model)) +
  facet_wrap(~bin_type, ncol = 3) +
  #scale_x_discrete(labels = c("bins", "gradual", "proximity")) +
 expand_limits(y = c(455, 480)) +
 theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "none",
       axis.text.x = element_blank(),
       panel.spacing = unit(0, "lines"),
        panel.border = element_blank(),
        strip.text = element_blank()) +
 geom_text(data = ann_text, aes(x = 1, y = 460, 
            label = " Wright2017"), col = "black") +
  scale_colour_viridis(discrete = TRUE, direction = -1, end = 0.8)   
```

Finally plot them all together

```{r}
# Using modified multiplot function
# written by Scott Chamberlain

pdf("../manuscript/figures/fig-peaks-epoch-appendix-revision.pdf")  
  multiplot(beck_peaks + theme(plot.margin=unit(c(5.5, 5.5, 5.5, 25),"points")), 
            brusatte_peaks + theme(plot.margin=unit(c(5.5, 5.5, 5.5, 25),"points")), 
            bapst_peaks + theme(plot.margin=unit(c(5.5, 5.5, 5.5, 25),"points")), 
            wright_peaks + theme(plot.margin=unit(c(5.5, 5.5, 20, 25),"points")),
            cols = 1,
            labs = list("Time bins or time slice method",
                        "Time at disparity peak (MYA)"),
            labpos = list(c(0.5, 0.015), c(0.03, 0.5)))
  

dev.off() 
```

# And for ages

```{r}

pdf("../manuscript/figures/fig-peaks-age-appendix-revision.pdf")  
  multiplot(beck_peaks_age + theme(plot.margin=unit(c(5.5, 5.5, 5.5, 25),"points")), 
            brusatte_peaks_age + theme(plot.margin=unit(c(5.5, 5.5, 5.5, 25),"points")), 
            bapst_peaks_age + theme(plot.margin=unit(c(5.5, 5.5, 5.5, 25),"points")), 
            wright_peaks_age + theme(plot.margin=unit(c(5.5, 5.5, 20, 25),"points")),
            cols = 1,
            labs = list("Time bins or time slice method",
                        "Time at disparity peak (MYA)"),
            labpos = list(c(0.5, 0.015), c(0.03, 0.5)))
  
dev.off()

```  
