---
title: "Figures compiler"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

# Compiling the figures for the paper

Loading the code:

```{r}
library(ape)
library(dispRity)
source("../functions/figures_fun.R")
```

## Disparity peaks figures (maximum/minimum)

Initialising the slug and loading the data:

Initialising the slug and loading the data:

```{r}
## Slugs (choose one)
slug <- "Beck2014"
# slug <- "Brusatte2014"
# slug <- "Bapst2016"
# slug <- "Wright2017"

## Load the data
data_max <- read.csv(paste0("../outputs/peaks.max.", slug, ".csv"), stringsAsFactors = FALSE)

## Get the relative age
relative_time <- read.nexus(file = paste0("../data/processed/tree.", slug, ".tre"))
if(slug == "Wright2017") {
    relative_time <- 484.4
} else {
    relative_time <- max(tree.age(relative_time)$age)
}
```

Single plots:

```{r, fig.width = 12, fig.height = 6}
op <- par(mfrow = c(1,2))
plot.max.min(data_max, relative.time = relative_time, xaxis = TRUE, yaxis = TRUE, pch = 19, main = "Relative age at maximum disparity in Beck2014")
plot.max.min(data_max, relative.time = relative_time, xaxis = TRUE, yaxis = TRUE, pch = 19, main = "Maximum disparity in Beck2014", what = "disparity", legend.coords = "bottomright")
par(op)
```

Multiple plots:

```{r, fig.width = 12, fig.height = 4}
## Names of the datasets
slugs <- as.list(c("Beck2014", "Brusatte2014", "Bapst2016", "Wright2017"))

## Load all the data
data_list_max <- lapply(slugs, function(slug) read.csv(paste0("../outputs/peaks.max.", slug, ".csv"), stringsAsFactors = FALSE))
data_list_min <- lapply(slugs, function(slug) read.csv(paste0("../outputs/peaks.min.", slug, ".csv"), stringsAsFactors = FALSE))

## Load the relative time
relative_times <- lapply(slugs, function(slug) read.nexus(file = paste0("../data/processed/tree.", slug, ".tre")))
relative_times <- lapply(relative_times, function(tree) max(tree.age(tree)$age))
relative_times[[4]] <- 484.4

## Set up the colours (to be changed)
colours <- palette()[1:7]

## Plot all maximum ages
multi.plot.max.min(data_list_max, what = c("age"), cols = colours, lty = c(1,2), pch = 19, adj = 0.1, relative.time = relative_times, legend = TRUE, names.data = unlist(slugs))

## Plot all maximum disparity
multi.plot.max.min(data_list_max, what = c("disparity"), cols = colours, lty = c(1,2), pch = 19, adj = 0.1, relative.time = relative_times, names.data = unlist(slugs))

## Plot all minimum ages
multi.plot.max.min(data_list_max, what = c("age"), cols = colours, lty = c(1,2), pch = 19, adj = 0.1, relative.time = relative_times, names.data = unlist(slugs))

## Plot all minimum disparity
multi.plot.max.min(data_list_max, what = c("disparity"), cols = colours, lty = c(1,2), pch = 19, adj = 0.1, relative.time = relative_times, names.data = unlist(slugs))

```




## Extinction effect figures

Initialising the slug and loading the data:

```{r}
## Slugs (choose one)
slug <- "Beck2014"
# slug <- "Brusatte2014"
# slug <- "Bapst2016"
# slug <- "Wright2017"

data <- read.csv(paste0("../outputs/extinction.", slug, ".csv"), stringsAsFactors = FALSE)
```

Single plots:

```{r, fig.width = 6, fig.height = 6}
colours <- c("grey", "white", "black") #Signif, non-signif, NA
plot.extinction(data, type = "age", xaxis = TRUE, yaxis = TRUE, xaxis2 = TRUE, main = slug, cols = colours)
```

Multiple plots:

```{r, fig.width = 12, fig.height = 4}
## Names of the datasets
slugs <- as.list(c("Beck2014", "Brusatte2014", "Bapst2016", "Wright2017"))

## Load all the data
data_list <- lapply(slugs, function(slug) read.csv(paste0("../outputs/extinction.", slug, ".csv"), stringsAsFactors = FALSE))

## Set up the colours (yeah, they're ugly for now)
colours <- c("lightblue", "yellow", "white") #Signif, non-signif, NA

## Plot all the results
multi.plot.extinction(data_list, type = c("age", "epoch"), data.names = unlist(slugs), cols = colours)
```


















