---
title: "Interesting results"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

# Some interesting results

Here's a good illustration of using stratigraphy number or duration on Brusatte's dataset.

```{r}
library(dispRity)
## Loading the data
slug <- "Brusatte2014"
out1 <- readRDS(file = paste0("../outputs/age.", slug, ".Rda"))
```

The red lines represent respectively (from left to right) the K-Pg (66 Mya) and the PETM (55.5 Mya).

```{r, fig.width = 12, fig.height = 12}

op <- par(mfrow = c(3,3))
## Stratigraphy
plot(out1$objects$stratigraphy[[1]], type = "p", main = "Brusatte2014 - bins/stratigraphy", ylim = c(5.5, 8.5))
abline(v = c(7.5, 9.5), col = "red")
plot(out1$objects$stratigraphy[[5]], main = "Brusatte2014 - proximity/stratigraphy", ylim = c(5.5, 8.5))
abline(v = c(6.5, 9.5), col = "red")
plot(out1$objects$stratigraphy[[7]], main = "Brusatte2014 - gradual.split/stratigraphy", ylim = c(5.5, 8.5))
abline(v = c(6.5, 9.5), col = "red")

## Duration
plot(out1$objects$duration[[1]], type = "p", main = "Brusatte2014 - bins/duration", ylim = c(5.5, 8.5))
abline(v = c(10.5, 13.5), col = "red")
plot(out1$objects$duration[[5]], main = "Brusatte2014 - proximity/duration", ylim = c(5.5, 8.5))
abline(v = c(10.5, 13.5), col = "red")
plot(out1$objects$duration[[7]], main = "Brusatte2014 - gradual.split/duration", ylim = c(5.5, 8.5))
abline(v = c(10.5, 13.5), col = "red")

## Stratigraphy
plot(out1$objects$number[[1]], type = "p", main = "Brusatte2014 - bins/number", ylim = c(5.5, 8.5))
abline(v = c(10.5, 13.5), col = "red")
plot(out1$objects$number[[5]], main = "Brusatte2014 - proximity/number", ylim = c(5.5, 8.5))
abline(v = c(6.5, 9.5), col = "red")
plot(out1$objects$number[[7]], main = "Brusatte2014 - gradual.split/number", ylim = c(5.5, 8.5))
abline(v = c(6.5, 9.5), col = "red")

par(op)
```
