---
title: "Table compiler"
author: "Thomas Guillerme"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_width: 12
    fig_height: 6
---

# Compiling the tables for the paper

Loading the packages

```{r}
library(xtable)
library(Claddis)
library(ape)
library(dispRity)
```

Loading the data:

```{r}
## Getting the data
slugs <- list("Beck2014", "Brusatte2014", "Bapst2016", "bears", "Wright2017")

## Matrices lists
matrices <- lapply(slugs, function(slug) ReadMorphNexus(paste0("../data/matrices/", slug, ".nex"))$matrix )

## Trees lists
trees <- lapply(slugs, function(slug) read.nexus(paste0("../data/processed/tree.", slug, ".tre")))
## Adding Wright's tree age
trees[[5]]$root.time <- 485.4
```

## Data set table


```{r}
## Column names
colnames <- c("Group", "n taxa", "m characters", "Age range", "Reference", "Notes")

## Dataset names
dataset <- unlist(slugs)
dataset[4] <- "Heath2016"

## Groups
group <- c("Eutherian mammals", "theropods", "theropods", "bears", "crinoids")

## Number of taxa
ntaxa <- unlist(lapply(matrices, nrow))

## Number of characters
mcharacters <- unlist(lapply(matrices, ncol))

## Age ranges
age_ranges <- lapply(trees, function(tree) rev(range(tree.age(tree)$age)))
age_ranges <- unlist(lapply(age_ranges, function(age) paste(age, collapse = " - ")))

## References and Notes (to be filled in LaTeX)
reference <- notes <- rep("", length(slugs))
notes[2] <- "2 + 9 taxa removed"
notes[3] <- "12 + 19 taxa removed. Tree was randomly selected from all time-scaled trees"
notes[4] <- "12 + 0 taxa removed"
notes[5] <-  "Maximum clade credibility tree, time-scaled by dividing branches by 0.03517385 and setting root time to 485.4"

## Formatting the table
table_out <- data.frame(group, ntaxa, mcharacters, age_ranges, reference, notes)
colnames(table_out) <- colnames
rownames(table_out) <- dataset

## Table caption
table_caption <- "Details of the datasets used in this study."

sink(file = "../manuscript/tables/datasets.tex")
xtable(table_out, caption = table_caption)
sink()
```

## Time subsets table


